<?php

defined('_JEXEC') or die;

JHtml::addIncludePath(JPATH_COMPONENT . '/helpers');

$app = JFactory::getApplication();
$doc = JFactory::getDocument();

$item = $this->item;
$params = $item->params;
$images = json_decode($item->images);
$urls = json_decode($item->urls);
$canEdit = $params->get('access-edit');
$user = JFactory::getUser();
$info = $params->get('info_block_position', 0);
$datetime = strtotime(JFactory::getDate());

// Rich Snippets
$doc->setMetaData('og:type', 'article', 'property');

// Check if associations are implemented. If they are, define the parameter.
$assocParam = (JLanguageAssociations::isEnabled() && $params->get('show_associations'));

// Is the article unpublished?
$unpublished = ($this->item->state == 0 || strtotime($this->item->publish_up) > $datetime
	              || ((strtotime($this->item->publish_down) < $datetime)
                && $this->item->publish_down != JFactory::getDbo()->getNullDate()));

$useDefList = ($params->get('show_modify_date')
             || $params->get('show_publish_date')
             || $params->get('show_create_date')
             || $params->get('show_hits')
             || $params->get('show_category')
             || $params->get('show_parent_category')
             || $params->get('show_author')
             || $assocParam);

JHtml::_('behavior.caption');

echo '<article class="item-page' . $this->pageclass_sfx . '" itemscope itemtype="https://schema.org/Article">';
echo '<meta itemprop="inLanguage" content="' . (($item->language === '*') ? JFactory::getConfig()->get('language') : $item->language) . '" />';
// Article Header
//echo $this->loadTemplate('header');
echo JLayoutHelper::render('yaniz.content.article.header', array('item' => $item, 'params' => $params, 'position' => 'above', 'print' => $this->print));

// Content is generated by content plugin event onContentAfterDisplay
echo $item->event->afterDisplayTitle;

/*
if ($useDefList && ($info == 0 || $info == 2)) {
  // Todo: for Joomla4 joomla.content.info_block.block can be changed to joomla.content.info_block
	echo JLayoutHelper::render('joomla.content.info_block.block', array('item' => $item, 'params' => $params, 'position' => 'above'));
}
*/
if ($info == 0 && $params->get('show_tags', 1) && !empty($item->tags->itemTags)) {
	$item->tagLayout = new JLayoutFile('joomla.content.tags');
  echo $item->tagLayout->render($item->tags->itemTags);
}

// Content is generated by content plugin event "onContentBeforeDisplay"
echo $item->event->beforeDisplayContent;

if (isset($urls)
    && ((!empty($urls->urls_position) && ($urls->urls_position == '0'))
        || ($params->get('urls_position') == '0' && empty($urls->urls_position)))
		|| (empty($urls->urls_position) && (!$params->get('urls_position')))) {

  echo $this->loadTemplate('links');
}

if ($params->get('access-view')) {
	echo JLayoutHelper::render('joomla.content.full_image', $item);

	if (!empty($item->pagination) && $item->pagination && !$item->paginationposition && !$item->paginationrelative) {
		echo $item->pagination;
	}

  if (isset ($item->toc)) {
		echo $item->toc;
  }

	echo '<div itemprop="articleBody">' . $item->text . '</div>';

	if ($info == 1 || $info == 2) {
		if ($useDefList) {
			// Todo: for Joomla4 joomla.content.info_block.block can be changed to joomla.content.info_block
			echo JLayoutHelper::render('yaniz.content.info', array('item' => $item, 'params' => $params, 'position' => 'below'));
		}

    if ($params->get('show_tags', 1) && !empty($item->tags->itemTags)) {
			$item->tagLayout = new JLayoutFile('joomla.content.tags');
			echo $item->tagLayout->render($item->tags->itemTags);
		}
	}

	if (!empty($item->pagination) && $item->pagination && $item->paginationposition && !$item->paginationrelative) {
		echo $item->pagination;
  }

	if (isset($urls) && ((!empty($urls->urls_position) && ($urls->urls_position == '1')) || ($params->get('urls_position') == '1'))) {
	   echo $this->loadTemplate('links');
  }

// Optional teaser intro text for guests
} elseif ($params->get('show_noauth') == true && $user->get('guest')) {
	echo $this->loadTemplate('teaser');
}

if (!empty($item->pagination) && $item->pagination && $item->paginationposition && $item->paginationrelative) {
		echo $item->pagination;
}

// Content is generated by content plugin event "onContentAfterDisplay"
echo $item->event->afterDisplayContent;

echo '</article>';
