<?php

defined('_JEXEC') or die;

$params = &$this->item->params;
$images = json_decode($this->item->images);
$canEdit = $this->item->params->get('access-edit');
$info = $this->item->params->get('info_block_position', 0);
$datetime = strtotime(JFactory::getDate());

// Check if associations are implemented. If they are, define the parameter.
$assocParam = (JLanguageAssociations::isEnabled() && $params->get('show_associations'));

// Is the article unpublished?
$unpublished = ($this->item->state == 0 || strtotime($this->item->publish_up) > $datetime
	              || ((strtotime($this->item->publish_down) < $datetime)
                && $this->item->publish_down != $this->db->getNullDate()));

// Todo Not that elegant would be nice to group the params
$useDefList = ($params->get('show_modify_date')
               || $params->get('show_publish_date')
               || $params->get('show_create_date')
               || $params->get('show_hits')
               || $params->get('show_category')
               || $params->get('show_parent_category')
               || $params->get('show_author')
               || $assocParam);

if ($unpublished) {
	echo '<div class="system-unpublished">';
}

if ($params->get('show_title')) {
	echo '<h2 class="item-title" itemprop="headline">';

  if ($params->get('link_titles') && $params->get('access-view')) {
	  echo '<a href="' . JRoute::_(ContentHelperRoute::getArticleRoute($this->item->slug, $this->item->catid, $this->item->language)) . '" itemprop="url">';
		echo $this->escape($this->item->title);
		echo '</a>';
	} else {
		echo $this->escape($this->item->title);
	}

  echo '</h2>';
}

if ($this->item->state == 0) {
  echo '<span class="label label-warning">' . JText::_('JUNPUBLISHED') . '</span>';
}

if (strtotime($this->item->publish_up) > strtotime(JFactory::getDate())) {
  echo '<span class="label label-warning">' . JText::_('JNOTPUBLISHEDYET') . '</span>';
}

if ((strtotime($this->item->publish_down) < strtotime(JFactory::getDate())) && $this->item->publish_down != JFactory::getDbo()->getNullDate()) {
  echo '<span class="label label-warning">' . JText::_('JEXPIRED') . '</span>';
}

if ($canEdit || $params->get('show_print_icon') || $params->get('show_email_icon')) {
  echo JLayoutHelper::render('joomla.content.icons', array('params' => $params, 'item' => $this->item, 'print' => false));
}

// Content is generated by content plugin event "onContentAfterTitle
echo $this->item->event->afterDisplayTitle;



if ($useDefList && ($info == 0 || $info == 2)) {
  // Todo: for Joomla4 joomla.content.info_block.block can be changed to joomla.content.info_block
  echo JLayoutHelper::render('joomla.content.info_block.block', array('item' => $this->item, 'params' => $params, 'position' => 'above'));
	if ($info == 0 && $params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) {
    echo JLayoutHelper::render('joomla.content.tags', $this->item->tags->itemTags);
  }
}

if (isset($images->image_intro) && !empty($images->image_intro)) {
  echo JLayoutHelper::render('joomla.content.intro_image', $this->item);
}

// Content is generated by content plugin event "onContentBeforeDisplay"
echo $this->item->event->beforeDisplayContent;

echo $this->item->introtext;

if ($useDefList && ($info == 1 || $info == 2)) {
	// Todo: for Joomla4 joomla.content.info_block.block can be changed to joomla.content.info_block
	echo JLayoutHelper::render('joomla.content.info_block.block', array('item' => $this->item, 'params' => $params, 'position' => 'below'));
	if ($params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) {
	   echo JLayoutHelper::render('joomla.content.tags', $this->item->tags->itemTags);
	}
}

if ($params->get('show_readmore') && $this->item->readmore) {
  echo $this->loadTemplate('readmore');
}

if ($unpublished) {
	echo '</div>';
}

// Content is generated by content plugin event "onContentAfterDisplay"
echo $this->item->event->afterDisplayContent;
